name: Invulnerability
version: 1.2.0
description: Provides temporary invulnerability to players when they connect/teleport/etc.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-invulnerability/
main: com.moltendorf.bukkit.invulnerability.Plugin
